Test feature service sendemailby csv
Batch-898-NickJurczak/qcforce-survey-service pull request #12
Opened 2021-01-03 21:02 UTC by chrisbreniser

2021-01-03 21:07 UTC, chrisbreniser commented on SurveyService/src/main/java/com/revature/service/AssociateService.java
> +
Add comment to method

2021-01-03 21:11 UTC, chrisbreniser commented on SurveyService/src/main/java/com/revature/service/SurveyService.java
> +	public boolean isValidSurvey(int surveyId);
comment method

2021-01-03 21:11 UTC, chrisbreniser commented on SurveyService/src/main/java/com/revature/service/SurveySubmissionService.java
> +
comment method

2021-01-03 21:15 UTC, chrisbreniser commented on SurveyService/src/test/java/com/revature/service/DistributionServiceImplTest.java
> +	Set<Integer> validAssociateIds;
Remove unused fields

2021-01-03 21:19 UTC, chrisbreniser commented on SurveyService/src/test/java/com/revature/service/DistributionServiceImplTest.java
> +		verify(associateService).getAssociatesByBatchId(batchId);
Dup verify unneeded.

2021-01-03 21:21 UTC, chrisbreniser commented on SurveyService/src/test/java/com/revature/service/DistributionServiceImplTest.java
> +		assertEquals(returned.getSendFailedEmails().size(), 0, "Returned EmailResponse with non-empty SendFailedEmails: " + returned.getSendFailedEmails().toString());
should throw IllegalArgumentException and not return

2021-01-03 21:34 UTC, chrisbreniser reviewed
Fix things. Few comments left.

2021-01-03 21:34 UTC, chrisbreniser commented on SurveyService/src/test/java/com/revature/service/DistributionServiceImplTest.java
> +
Not returning. Send InvalidSurveyIdException

2021-01-04 19:26 UTC, chrisbreniser commented on SurveyService/src/main/resources/application.yml
> +      uri: ${mongodb_url:mongodb+srv://test123:MongoTest123!@cluster0.fs9sm.mongodb.net/test?retryWrites=true&w=majority}
remove from yaml

2021-01-04 19:31 UTC, chrisbreniser commented on SurveyService/src/test/java/com/revature/service/DistributionServiceImplTest.java
> +			return;
assertThrows for each bad path.

2021-01-04 20:06 UTC, jurczakn requested changes

2021-01-04 20:06 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/dto/AssociateDto.java
> +package com.revature.dto;
remove from pr

2021-01-04 20:06 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/service/DistributionServiceImplTest.java
> +
when using this many verify methods, verify with description

2021-01-04 20:06 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/service/DistributionServiceImplTest.java
> +
verify it doesn't try to send out emails

2021-01-06 16:44 UTC, closed without merging