Feature email server
Batch-898-NickJurczak/qcforce-survey-service pull request #14
Opened 2021-01-04 16:22 UTC by mcawful

2021-01-04 19:51 UTC, jurczakn requested changes
clean up pr, all ignored files need to be removed

2021-01-04 19:51 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/SandBox.java
> +package com.revature;
remove

2021-01-06 23:47 UTC, jurczakn requested changes
.p12 file needs to be removed
remove commented out code

2021-01-06 23:47 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/SandBox.java
> +		//EmailResponse response = null;
remove commented out code

2021-01-06 23:56 UTC, chrisbreniser commented
Fixed requests:
- removed .p12 file. 
- deleted sandbox.java
- removed commented out code

2021-01-07 00:07 UTC, jurczakn approved these changes

2021-01-07 00:08 UTC, merged