Distribution initial test
Batch-898-NickJurczak/qcforce-survey-service pull request #2
Opened 2020-12-24 19:37 UTC by kmilstein

Created a interface for EmailService and changed the name of it to
EmailServiceImpl. Changed setEmailServiceMethod in EmailScheduler to
reflect name change. Created DistributionController and DistributionService
classes. Created tests for EmailService and DistributionController.

2020-12-24 19:56 UTC, jurczakn requested changes
update, and notify when fixed

2020-12-24 19:56 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/controller/DistributionController.java
> + * This controller takes in a batch id, or a batch id with a set of emails, then
Place validation description in Service where it belongs.  Have this specifically explain purpose of rest endpoints.

2020-12-24 19:56 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/controller/DistributionController.java
> +
not documented

2020-12-24 19:56 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/service/DistributionServiceImpl.java
> +
no documentation

2020-12-24 19:56 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/service/EmailServiceImpl.java
> +	 */
update method name to send email singular

2020-12-24 19:56 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/service/EmailService.java
change to send email singular

2020-12-24 19:56 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/controller/DistributionControllerTest.java
> +		MvcResult result = mockMvc.perform(request).andReturn();
add verification service is called

2020-12-24 19:56 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/controller/DistributionControllerTest.java
> +		MvcResult result = mockMvc.perform(request).andReturn();
check status code as well

2020-12-24 19:56 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/controller/DistributionControllerTest.java
> +@WebMvcTest
test for improperly formatted .csv

2020-12-24 19:56 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/controller/DistributionControllerTest.java
> +
comment test

2020-12-28 22:56 UTC, kmilstein commented on SurveyService/src/test/java/com/revature/controller/DistributionControllerTest.java
> +@WebMvcTest
Test has been added

2020-12-28 22:57 UTC, kmilstein commented on SurveyService/src/test/java/com/revature/controller/DistributionControllerTest.java
> +
Commends have been added

2020-12-28 22:59 UTC, kmilstein commented
Requested changes have been made.

2021-01-04 19:23 UTC, jurczakn requested changes

2021-01-04 19:23 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/controller/DistributionController.java
> +
add TODO comments

2021-01-04 19:23 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/controller/DistributionControllerTest.java
> +	private DistributionService service;
improve name

2021-01-04 19:23 UTC, jurczakn commented on SurveyService/src/main/java/com/revature/service/DistributionServiceImpl.java
> +	public List<String> sendEmailsByBatchIdAndCSV(int batchId, MultipartFile csv) {
have throw more specific exceptions

2021-01-06 23:19 UTC, jurczakn approved these changes

2021-01-06 23:19 UTC, merged