Distribution initial interfaces
Batch-898-NickJurczak/qcforce-survey-service pull request #8
Opened 2020-12-29 20:41 UTC by a-holliday

Ready for code review on CSVParser service, Email Service, and Auth Service tests, added documentation.

2021-01-04 19:43 UTC, jurczakn requested changes

2021-01-04 19:43 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/servicetest/AuthServiceJWTTest.java
> +	@Test
Spy on JWT parser, and verify appropriate methods were called to create token

2021-01-04 19:43 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/servicetest/AuthServiceJWTTest.java
> +
Rewrite tests, make sure they are testing what is actually being validated in this service

2021-01-04 19:43 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/servicetest/CSVParserTest.java
> +	 * Tests CSVParser service, creates a valid CSV and inputs it as parameter,
fix description, should be what this is testing, not what the test is doing

2021-01-04 19:43 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/servicetest/CSVParserTest.java
> +	 * FileNotFoundException.
if CSV file is invalid but there, why is it throwing a FNF exception

2021-01-04 19:43 UTC, jurczakn commented on SurveyService/src/test/java/com/revature/servicetest/CSVParserTest.java
> +@SpringBootTest
Test with more accurate data, we shouldn't have a batch with 3 associates

2021-01-06 23:20 UTC, jurczakn approved these changes

2021-01-06 23:47 UTC, kmilstein commented
Appears to be the same as branch feature-email-server

2021-01-06 23:47 UTC, closed without merging